"""Add serial_number and attributes to gifts and snapshots

Revision ID: 783fdbee8724
Revises: f066e3c8c963
Create Date: 2026-02-14 08:43:33.689287
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '783fdbee8724'
down_revision: Union[str, None] = 'f066e3c8c963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gifts_catalog', sa.Column('serial_number', sa.Integer(), nullable=True))
    op.add_column('gifts_catalog', sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('market_snapshots', sa.Column('serial_number', sa.Integer(), nullable=True))
    op.add_column('market_snapshots', sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_snapshots', 'attributes')
    op.drop_column('market_snapshots', 'serial_number')
    op.drop_column('gifts_catalog', 'attributes')
    op.drop_column('gifts_catalog', 'serial_number')
    # ### end Alembic commands ###
