"""initial

Revision ID: f066e3c8c963
Revises: 
Create Date: 2026-02-05 21:09:25.070641
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f066e3c8c963'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gifts_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('total_supply', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gifts_catalog_slug'), 'gifts_catalog', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('wallet_address', sa.String(length=100), nullable=True),
    sa.Column('subscription_level', sa.String(length=20), server_default='free', nullable=False),
    sa.Column('sub_expiry_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('tg_id')
    )
    op.create_table('deals',
    sa.Column('deal_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('initiator_tg_id', sa.BigInteger(), nullable=False),
    sa.Column('initiator_offer_type', sa.String(length=10), nullable=False),
    sa.Column('initiator_offer_slug', sa.String(length=100), nullable=True),
    sa.Column('initiator_wallet', sa.String(length=100), nullable=True),
    sa.Column('required_asset_type', sa.String(length=10), nullable=False),
    sa.Column('required_asset_slug', sa.String(length=100), nullable=True),
    sa.Column('required_token_contract', sa.String(length=100), nullable=True),
    sa.Column('required_amount', sa.Numeric(), nullable=True),
    sa.Column('service_wallet_address', sa.String(length=100), nullable=True),
    sa.Column('deposit_memo_code', sa.String(length=50), nullable=True),
    sa.Column('is_initiator_deposited', sa.Boolean(), nullable=False),
    sa.Column('is_counterparty_deposited', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['initiator_tg_id'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('deal_id'),
    sa.UniqueConstraint('deposit_memo_code')
    )
    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gift_slug', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('price_amount', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['gift_slug'], ['gifts_catalog.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_snapshots_slug_time', 'market_snapshots', ['gift_slug', 'scanned_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_snapshots_slug_time', table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_table('deals')
    op.drop_table('users')
    op.drop_index(op.f('ix_gifts_catalog_slug'), table_name='gifts_catalog')
    op.drop_table('gifts_catalog')
    # ### end Alembic commands ###
